name: Build and Deploy WAR

on:
  push:
    branches:
      - master
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    name: Build WAR
    runs-on: ubuntu-latest
    outputs:
      war-path: ${{ steps.upload.outputs.artifact-path }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build WAR
        run: |
          cd moi-mockup
          mvn clean package -DskipTests

      - name: Upload WAR artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: moi-mockup
          path: moi-mockup/target/*.war